# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: User.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nUser.proto\"K\n\rInsertRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0b\n\x03\x64ob\x18\x04 \x01(\t\"!\n\x0eStatusResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1a\n\x06\x44\x61taId\x12\x10\n\x08username\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"J\n\x0c\x44\x61taResponse\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0b\n\x03\x64ob\x18\x04 \x01(\t2\xcb\x01\n\x04User\x12+\n\x06Insert\x12\x0e.InsertRequest\x1a\x0f.StatusResponse\"\x00\x12!\n\x04List\x12\x06.Empty\x1a\r.DataResponse\"\x00\x30\x01\x12 \n\x04Show\x12\x07.DataId\x1a\r.DataResponse\"\x00\x12+\n\x06Update\x12\x0e.InsertRequest\x1a\x0f.StatusResponse\"\x00\x12$\n\x06\x44\x65lete\x12\x07.DataId\x1a\x0f.StatusResponse\"\x00\x62\x06proto3')



_INSERTREQUEST = DESCRIPTOR.message_types_by_name['InsertRequest']
_STATUSRESPONSE = DESCRIPTOR.message_types_by_name['StatusResponse']
_DATAID = DESCRIPTOR.message_types_by_name['DataId']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_DATARESPONSE = DESCRIPTOR.message_types_by_name['DataResponse']
InsertRequest = _reflection.GeneratedProtocolMessageType('InsertRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSERTREQUEST,
  '__module__' : 'User_pb2'
  # @@protoc_insertion_point(class_scope:InsertRequest)
  })
_sym_db.RegisterMessage(InsertRequest)

StatusResponse = _reflection.GeneratedProtocolMessageType('StatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATUSRESPONSE,
  '__module__' : 'User_pb2'
  # @@protoc_insertion_point(class_scope:StatusResponse)
  })
_sym_db.RegisterMessage(StatusResponse)

DataId = _reflection.GeneratedProtocolMessageType('DataId', (_message.Message,), {
  'DESCRIPTOR' : _DATAID,
  '__module__' : 'User_pb2'
  # @@protoc_insertion_point(class_scope:DataId)
  })
_sym_db.RegisterMessage(DataId)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'User_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

DataResponse = _reflection.GeneratedProtocolMessageType('DataResponse', (_message.Message,), {
  'DESCRIPTOR' : _DATARESPONSE,
  '__module__' : 'User_pb2'
  # @@protoc_insertion_point(class_scope:DataResponse)
  })
_sym_db.RegisterMessage(DataResponse)

_USER = DESCRIPTOR.services_by_name['User']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INSERTREQUEST._serialized_start=14
  _INSERTREQUEST._serialized_end=89
  _STATUSRESPONSE._serialized_start=91
  _STATUSRESPONSE._serialized_end=124
  _DATAID._serialized_start=126
  _DATAID._serialized_end=152
  _EMPTY._serialized_start=154
  _EMPTY._serialized_end=161
  _DATARESPONSE._serialized_start=163
  _DATARESPONSE._serialized_end=237
  _USER._serialized_start=240
  _USER._serialized_end=443
# @@protoc_insertion_point(module_scope)
